jblog:
  datasource:
    # jdbc: "jdbc:h2:mem:test;MODE=MYSQL;DB_CLOSE_DELAY=-1"
    jdbc: "jdbc:mysql://localhost:3306/jblog"
    username: root
    password: 1234
    show-sql: true
    mode: update
    create-ddl-script: false
  cors:
    - "*"
  datafixture: false
  
logging:  file: /temp/jblog.log